import { closeSync, existsSync, fsyncSync, lstatSync, mkdirSync, openSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { basename, dirname, relative, resolve, sep } from "node:path";
import { assertLiveProjectLock, assertLiveWorkspaceOutputLock, assertPinnedEntry, pinPhysicalDirectory, pinPhysicalEntry } from "../state/project-lock.mjs";
import { assertCurrentProjectIdentity } from "../books/discovery.mjs";
import { openStateDatabase } from "../state/database.mjs";

const PHASES = new Set(["prepared", "backup-intent", "backup-complete", "activate-intent", "activate-complete", "material-verified", "ledger-completed", "commit-cleanup-intent", "commit-cleanup-complete", "rollback-quarantine-intent", "rollback-quarantine-complete", "rollback-restore-intent", "rollback-restore-complete", "rollback-cleanup-intent", "rollback-cleanup-complete"]);
const SAFE_ID = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const exactKeys = (value, keys) => value && typeof value === "object" && !Array.isArray(value) && Object.keys(value).sort().join("\0") === [...keys].sort().join("\0");
const event = (hook, name, context) => hook?.(name, context);
function syncDirectory(directory) { const fd = openSync(directory, "r"); try { fsyncSync(fd); } finally { closeSync(fd); } }
function safeIdentity(projectId, releaseId, token) { if (!SAFE_ID.test(projectId) || !SAFE_ID.test(releaseId) || !UUID.test(token)) throw new Error("Promotion identity must use safe project/release IDs and a cryptographically random UUID token."); }
function inside(root, path) { const value = relative(resolve(root), resolve(path)); return value !== ".." && !value.startsWith(`..${sep}`); }
function digest(bytes) { return createHash("sha256").update(bytes).digest("hex"); }
function pathRecord(path, { recursive = false } = {}) {
  if (!existsSync(path)) return Object.freeze({ path, missing: true });
  const entry = lstatSync(path); if (entry.isSymbolicLink()) throw new Error(`Promotion paths cannot be symbolic links: ${path}`);
  if (entry.isFile()) { if (entry.nlink !== 1) throw new Error(`Promotion file must be private: ${path}`); const bytes = readFileSync(path); return Object.freeze({ path, missing: false, type: "file", identity: pinPhysicalEntry(path, "file"), hash: digest(bytes), bytes: bytes.length }); }
  if (!entry.isDirectory()) throw new Error(`Promotion path has an unsupported type: ${path}`);
  const children = recursive ? readdirSync(path).sort().map((name) => pathRecord(resolve(path, name), { recursive: true })) : null;
  return Object.freeze({ path, missing: false, type: "directory", identity: pinPhysicalEntry(path, "directory"), children });
}
function assertRecord(record, { at = record.path } = {}) {
  if (record.missing) { if (existsSync(at)) throw new Error(`Promotion transaction identity changed: ${at}`); return; }
  const current = pinPhysicalEntry(at, record.type); if (current.dev !== record.identity.dev || current.ino !== record.identity.ino) throw new Error(`Promotion transaction identity changed: ${at}`);
  if (record.type === "file") { const bytes = readFileSync(at); if (bytes.length !== record.bytes || digest(bytes) !== record.hash) throw new Error(`Promotion transaction bytes changed: ${at}`); return; }
  if (!record.children) return;
  const names = readdirSync(at).sort(); if (names.length !== record.children.length) throw new Error(`Promotion transaction contents changed: ${at}`);
  for (let index = 0; index < names.length; index += 1) { if (basename(record.children[index].path) !== names[index]) throw new Error(`Promotion transaction contents changed: ${at}`); assertRecord(record.children[index], { at: resolve(at, names[index]) }); }
}
function contextFor(input) {
  const { outputRoot, projectId, releaseId, token } = input; safeIdentity(projectId, releaseId, token);
  const root = resolve(outputRoot), stagingRoot = resolve(root, ".staging"), stateRoot = resolve(root, ".promotion-state"), projectRoot = resolve(root, projectId);
  const context = { outputRoot: root, projectId, releaseId, token, staging: resolve(stagingRoot, `${projectId}-${token}`), target: resolve(projectRoot, releaseId), backup: resolve(stateRoot, `${projectId}-${releaseId}-${token}.backup`), quarantine: resolve(stateRoot, `${projectId}-${releaseId}-${token}.quarantine`), marker: resolve(stateRoot, `${projectId}-${releaseId}-${token}.json`) };
  if (![context.staging, context.target, context.backup, context.quarantine, context.marker].every((path) => inside(root, path))) throw new Error("Promotion paths escape the trusted output root.");
  return context;
}
function transactionPaths(context) { return [...new Set([context.outputRoot, dirname(context.staging), dirname(context.target), dirname(context.marker), context.staging, context.target, context.backup, context.quarantine, context.marker])]; }
function initialAuthority(context) { const ownedTrees = new Set([context.staging, context.target, context.backup, context.quarantine]); return transactionPaths(context).map((path) => pathRecord(path, { recursive: ownedTrees.has(path) })); }
function assertSnapshot(records) { for (const record of records) assertRecord(record); }
function validateUnchanged(records, changed) { for (const record of records) if (!changed.has(record.path)) assertRecord(record); }
function rebase(record, path) { if (record.missing) return Object.freeze({ path, missing: true }); if (record.type === "file") return Object.freeze({ ...record, path, identity: Object.freeze({ ...record.identity, path }) }); return Object.freeze({ ...record, path, identity: Object.freeze({ ...record.identity, path }), children: record.children?.map((child) => rebase(child, resolve(path, basename(child.path)))) ?? null }); }
function serializeRecord(record, root) { if (record.missing) return { path: relative(root, record.path), missing: true }; const base = { path: relative(root, record.path), missing: false, type: record.type, dev: record.identity.dev, ino: record.identity.ino }; if (record.type === "file") return { ...base, bytes: record.bytes, hash: record.hash }; return { ...base, children: record.children?.map((child) => serializeRecord(child, root)) ?? null }; }
function deserializeRecord(value, root) { if (!value || typeof value.path !== "string" || typeof value.missing !== "boolean") throw new Error("Promotion recovery evidence is malformed."); const path = resolve(root, value.path); if (!inside(root, path)) throw new Error("Promotion recovery evidence escapes its root."); if (value.missing) { if (!exactKeys(value, ["path", "missing"])) throw new Error("Promotion recovery evidence is malformed."); return Object.freeze({ path, missing: true }); } if (!Number.isInteger(value.dev) || !Number.isInteger(value.ino) || !["file", "directory"].includes(value.type)) throw new Error("Promotion recovery evidence is malformed."); const identity = Object.freeze({ path, dev: value.dev, ino: value.ino }); if (value.type === "file") { if (!exactKeys(value, ["path", "missing", "type", "dev", "ino", "bytes", "hash"]) || !Number.isInteger(value.bytes) || typeof value.hash !== "string") throw new Error("Promotion recovery evidence is malformed."); return Object.freeze({ path, missing: false, type: "file", identity, bytes: value.bytes, hash: value.hash }); } if (!exactKeys(value, ["path", "missing", "type", "dev", "ino", "children"]) || value.children !== null && !Array.isArray(value.children)) throw new Error("Promotion recovery evidence is malformed."); return Object.freeze({ path, missing: false, type: "directory", identity, children: value.children?.map((child) => deserializeRecord(child, root)) ?? null }); }
function expectedUpdate(authority, updates) { return authority.map((record) => updates.get(record.path) ?? record); }
function expectedRename(authority, source, target) { const sourceRecord = authority.find((record) => record.path === source), targetRecord = authority.find((record) => record.path === target); if (!sourceRecord || sourceRecord.missing || !targetRecord?.missing) return null; return expectedUpdate(authority, new Map([[source, Object.freeze({ path: source, missing: true })], [target, rebase(sourceRecord, target)]])); }
function expectedRemove(authority, path) { return expectedUpdate(authority, new Map([[path, Object.freeze({ path, missing: true })]])); }
function recoveryCandidates(authority, context, phase) { const candidates = [authority], add = (candidate) => { if (candidate) candidates.push(candidate); }; if (phase === "backup-intent") add(expectedRename(authority, context.target, context.backup)); if (phase === "activate-intent") add(expectedRename(authority, context.staging, context.target)); if (phase === "rollback-quarantine-intent") add(expectedRename(authority, context.target, context.quarantine)); if (phase === "rollback-restore-intent") add(expectedRename(authority, context.backup, context.target)); if (phase === "commit-cleanup-intent") add(expectedRemove(authority, context.backup)); if (phase === "rollback-cleanup-intent") { const withoutQuarantine = expectedRemove(authority, context.quarantine), withoutStaging = expectedRemove(authority, context.staging); add(withoutQuarantine); add(withoutStaging); add(expectedRemove(withoutQuarantine, context.staging)); } return candidates; }
function readMarker(context) { const bytes = readFileSync(context.marker), value = JSON.parse(bytes.toString("utf8")); if (!exactKeys(value, ["schemaVersion", "projectId", "releaseId", "token", "phase", "hadPrior", "evidence"]) || value.schemaVersion !== 2 || value.projectId !== context.projectId || value.releaseId !== context.releaseId || value.token !== context.token || !PHASES.has(value.phase) || typeof value.hadPrior !== "boolean" || !Array.isArray(value.evidence) || !bytes.equals(Buffer.from(`${JSON.stringify(value)}\n`))) throw new Error("Promotion recovery marker is malformed or mismatched; no filesystem mutation was performed."); const expectedPaths = transactionPaths(context).filter((path) => path !== context.marker).sort(), evidence = value.evidence.map((record) => deserializeRecord(record, context.outputRoot)); if (evidence.map((record) => record.path).sort().join("\0") !== expectedPaths.join("\0")) throw new Error("Promotion recovery evidence does not bind every transaction path."); let matched = null; for (const candidate of recoveryCandidates(evidence, context, value.phase)) { try { assertSnapshot(candidate); matched = candidate; break; } catch {} } if (!matched) throw new Error("Promotion recovery state does not match marker-bound pre-state or an allowed exact transition."); const marker = pathRecord(context.marker); if (marker.type !== "file" || marker.hash !== digest(bytes)) throw new Error("Promotion recovery marker identity changed."); return { context: { ...context, phase: value.phase, hadPrior: value.hadPrior }, authority: [...matched, marker] }; }
function markerValue(context, phase, hadPrior, authority) { return { schemaVersion: 2, projectId: context.projectId, releaseId: context.releaseId, token: context.token, phase, hadPrior, evidence: authority.filter((record) => record.path !== context.marker).map((record) => serializeRecord(record, context.outputRoot)) }; }

function createEngine(initial, locks, hook, recoveredAuthority = null) {
  let context = initial, authority = recoveredAuthority ?? initialAuthority(initial);
  function guard() { assertLiveWorkspaceOutputLock(locks.workspaceLock, locks.workspaceRoot); assertLiveProjectLock(locks.projectLock, locks.projectRoot); assertSnapshot(authority); }
  function advance(next = context, updates = new Map()) { const expected = authority.map((record) => updates.get(record.path) ?? record); event(hook, "before-authority-advance", next); try { assertSnapshot(expected); } catch (error) { error.recoveryRequired = true; throw error; } context = next; authority = expected; return context; }
  function renameOwned(source, target, label) {
    guard(); const before = authority, sourceRecord = pathRecord(source, { recursive: true }), targetRecord = pathRecord(target); if (sourceRecord.missing || !targetRecord.missing) throw new Error(`Promotion ${label} requires one pinned source and a missing destination.`);
    renameSync(source, target); syncDirectory(dirname(source)); if (dirname(target) !== dirname(source)) syncDirectory(dirname(target)); event(hook, `after-atomic-${label}`, context);
    const missing = Object.freeze({ path: source, missing: true }), moved = rebase(sourceRecord, target); validateUnchanged(before, new Set([source, target])); assertRecord(missing); assertRecord(moved); advance(context, new Map([[source, missing], [target, moved]]));
  }
  function removeOwned(path, options, label) {
    guard(); const before = authority, owned = pathRecord(path); if (owned.missing) return;
    rmSync(path, options); syncDirectory(dirname(path)); event(hook, `after-atomic-${label}`, context);
    const missing = Object.freeze({ path, missing: true }); validateUnchanged(before, new Set([path])); assertRecord(missing); advance(context, new Map([[path, missing]]));
  }
  function ensureOwned(directory, label) {
    guard(); const before = authority; if (existsSync(directory)) { assertRecord(pathRecord(directory)); return; }
    const missing = []; let cursor = directory; while (!existsSync(cursor)) { missing.push(cursor); cursor = dirname(cursor); } const ancestor = pathRecord(cursor); mkdirSync(directory, { recursive: true, mode: 0o700 }); syncDirectory(directory); syncDirectory(cursor); const created = missing.map((path) => pathRecord(path)); event(hook, `after-atomic-${label}`, context);
    assertRecord(ancestor); validateUnchanged(before, new Set(missing)); for (const record of created) assertRecord(record); advance(context, new Map(created.map((record) => [record.path, record])));
  }
  function writeMarker(phase, hadPrior) {
    guard(); event(hook, `before-marker-${phase}`, context); guard(); ensureOwned(dirname(context.marker), `ensure-marker-parent-${phase}`); guard();
    const before = authority, value = markerValue(context, phase, hadPrior, authority), bytes = Buffer.from(`${JSON.stringify(value)}\n`), temporary = `${context.marker}.${process.pid}.${Date.now()}.tmp`; if (existsSync(temporary)) throw new Error("Promotion marker temporary path already exists.");
    const fd = openSync(temporary, "wx", 0o600); try { writeFileSync(fd, bytes); fsyncSync(fd); } finally { closeSync(fd); } const owned = pathRecord(temporary); if (owned.hash !== digest(bytes) || owned.bytes !== bytes.length) throw new Error("Promotion marker temporary bytes changed before rename.");
    renameSync(temporary, context.marker); syncDirectory(dirname(context.marker)); event(hook, `after-atomic-marker-${phase}`, context);
    const marker = rebase(owned, context.marker); validateUnchanged(before, new Set([context.marker])); assertRecord({ path: temporary, missing: true }); assertRecord(marker); const next = { ...context, phase, hadPrior }; advance(next, new Map([[context.marker, marker]])); event(hook, `after-marker-${phase}`, context); return context;
  }
  function removeMarker() { event(hook, "before-marker-cleanup", context); removeOwned(context.marker, { force: true }, "marker-cleanup"); event(hook, "after-marker-cleanup", context); }
  function rollbackFromCurrent() {
    guard(); context = writeMarker("rollback-quarantine-intent", context.hadPrior); event(hook, "before-target-quarantine", context); if (existsSync(context.target) && !existsSync(context.quarantine)) renameOwned(context.target, context.quarantine, "target-quarantine"); event(hook, "after-target-quarantine", context);
    context = writeMarker("rollback-quarantine-complete", context.hadPrior); context = writeMarker("rollback-restore-intent", context.hadPrior); event(hook, "before-backup-restore", context); if (context.hadPrior && existsSync(context.backup) && !existsSync(context.target)) renameOwned(context.backup, context.target, "backup-restore"); event(hook, "after-backup-restore", context);
    context = writeMarker("rollback-restore-complete", context.hadPrior); context = writeMarker("rollback-cleanup-intent", context.hadPrior); event(hook, "before-quarantine-cleanup", context); if (existsSync(context.quarantine)) removeOwned(context.quarantine, { recursive: true, force: true }, "quarantine-cleanup"); if (existsSync(context.staging)) removeOwned(context.staging, { recursive: true, force: true }, "staging-cleanup"); event(hook, "after-quarantine-cleanup", context);
    context = writeMarker("rollback-cleanup-complete", context.hadPrior); removeMarker(); return context;
  }
  function finishRollback() {
    const early = new Set(["prepared", "backup-intent"]); if (early.has(context.phase) && !existsSync(context.backup)) { if (existsSync(context.staging)) removeOwned(context.staging, { recursive: true, force: true }, "staging-cleanup"); removeMarker(); return context; }
    if (!["rollback-quarantine-complete", "rollback-restore-intent", "rollback-restore-complete", "rollback-cleanup-intent", "rollback-cleanup-complete"].includes(context.phase)) { context = writeMarker("rollback-quarantine-intent", context.hadPrior); if (existsSync(context.target) && !existsSync(context.quarantine)) renameOwned(context.target, context.quarantine, "target-quarantine"); context = writeMarker("rollback-quarantine-complete", context.hadPrior); }
    if (!["rollback-restore-complete", "rollback-cleanup-intent", "rollback-cleanup-complete"].includes(context.phase)) { context = writeMarker("rollback-restore-intent", context.hadPrior); if (context.hadPrior && existsSync(context.backup) && !existsSync(context.target)) renameOwned(context.backup, context.target, "backup-restore"); context = writeMarker("rollback-restore-complete", context.hadPrior); }
    context = writeMarker("rollback-cleanup-intent", context.hadPrior); if (existsSync(context.quarantine)) removeOwned(context.quarantine, { recursive: true, force: true }, "quarantine-cleanup"); if (existsSync(context.staging)) removeOwned(context.staging, { recursive: true, force: true }, "staging-cleanup"); context = writeMarker("rollback-cleanup-complete", context.hadPrior); removeMarker(); return context;
  }
  return {
    begin() { guard(); if (!existsSync(context.staging)) throw new Error("Promotion staging directory is missing."); if (existsSync(context.marker) || existsSync(context.backup) || existsSync(context.quarantine)) throw new Error("Promotion state already exists; recover it before starting another transaction."); ensureOwned(dirname(context.target), "ensure-target-parent"); const hadPrior = existsSync(context.target); context = writeMarker("prepared", hadPrior); context = writeMarker("backup-intent", hadPrior); event(hook, "before-old-to-backup", context); if (hadPrior) renameOwned(context.target, context.backup, "old-to-backup"); event(hook, "after-old-to-backup", context); context = writeMarker("backup-complete", hadPrior); context = writeMarker("activate-intent", hadPrior); event(hook, "before-staging-to-target", context); renameOwned(context.staging, context.target, "staging-to-target"); event(hook, "after-staging-to-target", context); return writeMarker("activate-complete", hadPrior); },
    markMaterialVerified() { return writeMarker("material-verified", context.hadPrior); },
    markLedgerCompleted() { return writeMarker("ledger-completed", context.hadPrior); },
    commit() { guard(); if (context.phase !== "ledger-completed") throw new Error("Promotion cleanup requires durable ledger completion authority."); context = writeMarker("commit-cleanup-intent", context.hadPrior); event(hook, "before-backup-cleanup", context); if (existsSync(context.backup)) removeOwned(context.backup, { recursive: true, force: true }, "backup-cleanup"); event(hook, "after-backup-cleanup", context); context = writeMarker("commit-cleanup-complete", context.hadPrior); removeMarker(); return context; },
    rollback() { return rollbackFromCurrent(); },
    recover() { guard(); if (!existsSync(context.marker)) return { state: "none", context }; guard(); if (context.phase === "material-verified") return { state: "completion-required", context }; if (["ledger-completed", "commit-cleanup-intent", "commit-cleanup-complete"].includes(context.phase)) { if (context.phase === "ledger-completed") context = writeMarker("commit-cleanup-intent", context.hadPrior); if (existsSync(context.backup)) removeOwned(context.backup, { recursive: true, force: true }, "backup-cleanup"); if (context.phase !== "commit-cleanup-complete") context = writeMarker("commit-cleanup-complete", context.hadPrior); removeMarker(); return { state: "committed", context }; } context = finishRollback(); return { state: "rolled-back", context }; },
    assertStable() { guard(); return true; }, context() { return { ...context }; }, paths() { return { ...context }; },
  };
}

function markerContexts(outputRoot, projectId, releaseId) { const root = resolve(outputRoot, ".promotion-state"); if (!existsSync(root)) return []; const entry = lstatSync(root); if (entry.isSymbolicLink() || !entry.isDirectory()) throw new Error("Promotion state root is unsafe."); return readdirSync(root).filter((name) => name.startsWith(`${projectId}-${releaseId}-`) && name.endsWith(".json")).sort().map((name) => { const token = basename(name, ".json").slice(`${projectId}-${releaseId}-`.length); return contextFor({ outputRoot, projectId, releaseId, token }); }); }

export function openCanonicalPromotion({ workspaceRoot, projectRoot, project, candidate, manifest, releaseId, token, workspaceLock, projectLock, hook }) {
  const projectId = project?.id;
  if (!SAFE_ID.test(projectId) || !SAFE_ID.test(releaseId) || releaseId !== manifest?.releaseId || candidate?.candidateHash !== manifest?.candidateHash || manifest?.projectId !== projectId) throw new Error("Canonical promotion identity is incomplete or mismatched."); assertLiveWorkspaceOutputLock(workspaceLock, workspaceRoot); assertLiveProjectLock(projectLock, projectRoot); assertCurrentProjectIdentity(project);
  const workspace = pinPhysicalDirectory(workspaceRoot).path, physicalProject = pinPhysicalDirectory(projectRoot).path, declaredProject = pinPhysicalDirectory(project.legacyRoot).path, rel = relative(workspace, physicalProject); if (rel === ".." || rel.startsWith(`..${sep}`) || declaredProject !== physicalProject) throw new Error("Promotion project must be the declared project inside the locked workspace.");
  const database = openStateDatabase(resolve(physicalProject, ".rtb-state", "state.sqlite")); try { const finalization = database.prepare("SELECT * FROM release_finalizations WHERE release_id = ?").get(releaseId), identity = database.prepare("SELECT * FROM release_identities WHERE release_id = ?").get(releaseId), registered = database.prepare("SELECT candidate_json FROM release_candidates WHERE candidate_hash = ? AND project_id = ?").get(candidate.candidateHash, projectId); if (!finalization || !identity || !registered || finalization.project_id !== projectId || finalization.candidate_hash !== candidate.candidateHash || finalization.manifest_hash !== manifest.manifestHash || finalization.manifest_json !== JSON.stringify(manifest) || !["pending", "completed"].includes(finalization.status) || identity.project_id !== projectId || identity.candidate_hash !== candidate.candidateHash || !["pending", "completed"].includes(identity.status) || registered.candidate_json !== JSON.stringify(candidate)) throw new Error("Promotion requires exact durable candidate, identity, and finalization authority."); } finally { database.close(); }
  const outputRoot = resolve(workspace, "dist", "releases", "immutable"), locks = { workspaceRoot: workspace, projectRoot: physicalProject, workspaceLock, projectLock }, initial = contextFor({ outputRoot, projectId, releaseId, token }); let engine = createEngine(initial, locks, hook);
  return Object.freeze({
    begin() { return engine.begin(); }, markMaterialVerified() { return engine.markMaterialVerified(); }, markLedgerCompleted() { return engine.markLedgerCompleted(); }, commit() { return engine.commit(); }, rollback() { return engine.rollback(); }, assertStable() { return engine.assertStable(); }, context() { return engine.context(); }, paths() { return engine.paths(); },
    recoverPending({ rollbackCompletionRequired = false } = {}) { const results = []; for (const pending of markerContexts(outputRoot, projectId, releaseId)) { const recoveredState = readMarker(pending); engine = createEngine(recoveredState.context, locks, hook, recoveredState.authority); const recovered = engine.recover(); if (recovered.state === "completion-required" && rollbackCompletionRequired) { engine.rollback(); results.push({ state: "rolled-back", context: engine.context() }); } else results.push(recovered); } return results; },
  });
}
