import { chmodSync, copyFileSync, lstatSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { relative, resolve } from "node:path";
import { assembleBook } from "../books/assemble.mjs";
import { ROOT } from "../lib.mjs";
import { command, fileHashChunked, materialHash, repositoryPath, sha256, writeJson } from "./common.mjs";

const transformerFiles = () => readdirSync(resolve(ROOT, "scripts", "publishing")).filter((name) => name.endsWith(".mjs")).sort().map((name) => resolve(ROOT, "scripts", "publishing", name));
function safeFiles(root, directory = root) { const files = []; for (const entry of readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) { if ([".rtb-content", ".rtb-state", "outputs"].includes(entry.name)) continue; const file = resolve(directory, entry.name); if (entry.isSymbolicLink()) throw new Error(`Release snapshot rejects symbolic links: ${file}`); if (entry.isDirectory()) files.push(...safeFiles(root, file)); else if (entry.isFile()) files.push(file); } return files; }
export function snapshotMaterials(project, tools) {
  const canonical = safeFiles(project.root);
  const configuration = [resolve(ROOT, ".github", "workflows", "publishing.yml"), resolve(ROOT, "package.json"), resolve(ROOT, "governance", "RFC", "RFC-007-Research-to-Book-Publishing.md"), resolve(ROOT, "governance", "RFC", "RFC-008-PDF-Publication-Profile.md"), resolve(ROOT, "governance", "ADR", "ADR-012-Immutable-Releases-and-Ghost-Adapter.md"), resolve(ROOT, "scripts", "lib.mjs"), resolve(ROOT, "scripts", "mermaid.mjs"), resolve(ROOT, "scripts", "book-contract.mjs"), resolve(ROOT, "scripts", "verify-outputs.mjs"), resolve(ROOT, "scripts", "books", "assemble.mjs"), resolve(ROOT, "scripts", "books", "discovery.mjs"), resolve(ROOT, "scripts", "books", "model.mjs"), resolve(ROOT, "publishing", "styles.css"), resolve(ROOT, "publishing", "epub.css"), resolve(ROOT, "publishing", "pdf", "toolchain.lock.json"), resolve(ROOT, "publishing", "epub", "toolchain.lock.json"), resolve(ROOT, "pnpm-lock.yaml"), ...transformerFiles()];
  const pandoc = command("which", ["pandoc"]).stdout.trim(), mmdc = resolve(ROOT, "node_modules", ".bin", "mmdc");
  const toolRecords = [{ name: "pandoc", version: command(pandoc, ["--version"]).stdout.split(/\r?\n/)[0], sha256: fileHashChunked(pandoc) }, { name: "mermaid-cli", version: command(mmdc, ["--version"]).stdout.trim(), sha256: fileHashChunked(mmdc) }, { name: "typst", version: command(tools.typst, ["--version"]).stdout.trim(), sha256: fileHashChunked(tools.typst) }, { name: "java", version: command(tools.java, ["-version"], { allowFailure: true }).stderr.trim().split(/\r?\n/)[0], sha256: fileHashChunked(tools.java) }, { name: "verapdf-jar", version: "1.28.2", sha256: fileHashChunked(tools.jar) }, { name: "epubcheck-archive", version: "5.3.0", sha256: fileHashChunked(tools.epubArchive) }, { name: "epubcheck-jar", version: "5.3.0", sha256: fileHashChunked(tools.epubJar) }, { name: "font:Noto Serif", version: "locked", sha256: fileHashChunked(tools.font) }];
  const repository = { revision: command("git", ["rev-parse", "HEAD"]).stdout.trim(), tree: command("git", ["rev-parse", "HEAD^{tree}"]).stdout.trim() };
  return { repository, canonical: canonical.map((file) => ({ path: relative(project.root, file).split("\\").join("/"), sha256: fileHashChunked(file) })), configuration: configuration.map((file) => ({ path: repositoryPath(file), sha256: fileHashChunked(file) })), tools: toolRecords };
}
function acceptedDiagramDirectory(project) { const assets = resolve(project.root, project.manifest.paths.assets), registryFile = resolve(assets, "diagram-registry.json"); if (!statSync(registryFile, { throwIfNoEntry: false })) return null; const registry = JSON.parse(readFileSync(registryFile, "utf8")), expected = []; for (const chapter of project.chapters) { let index = 0; for (const match of readFileSync(chapter.sourcePath, "utf8").matchAll(/```mermaid\s*\n([\s\S]*?)```/g)) { index += 1; expected.push({ chapterId: chapter.id, index, sourceSha256: sha256(`${match[1].trim()}\n`) }); } } if (!Array.isArray(registry.entries) || registry.entries.length !== expected.length) throw new Error("Accepted diagram registry does not cover every canonical Mermaid block."); for (const item of expected) { const record = registry.entries.find((entry) => entry.chapterId === item.chapterId && entry.index === item.index), expectedImage = `assets/diagrams/${item.chapterId}-diagram-${item.index}.png`; if (!record || record.image !== expectedImage || record.sourceSha256 !== item.sourceSha256) throw new Error(`Accepted diagram is stale or mismatched: ${item.chapterId} diagram ${item.index}`); const image = resolve(project.root, expectedImage); if (!lstatSync(image).isFile() || lstatSync(image).isSymbolicLink() || fileHashChunked(image) !== record.imageSha256) throw new Error(`Accepted diagram is unsafe, stale, or mismatched: ${item.chapterId} diagram ${item.index}`); } return resolve(assets, "diagrams"); }
export function prepareSnapshot(project, directory, { tools } = {}) {
  const root = resolve(directory); const diagrams = resolve(root, "diagrams"); mkdirSync(diagrams, { recursive: true });
  const assembled = assembleBook(project, { diagramsDirectory: diagrams, preRenderedDirectory: acceptedDiagramDirectory(project) });
  writeFileSync(resolve(root, "book.md"), assembled.markdown.replaceAll("☐", "[ ]"));
  copyFileSync(resolve(ROOT, "publishing", "styles.css"), resolve(root, "styles.css"));
  copyFileSync(resolve(ROOT, "publishing", "epub.css"), resolve(root, "epub.css"));
  const materials = snapshotMaterials(project, tools); const sourceFingerprint = materialHash(materials), names = ["book.md", "styles.css", "epub.css", ...readdirSync(diagrams).sort().map((name) => `diagrams/${name}`)];
  const record = { schemaVersion: 1, projectId: project.id, authority: project.authority, canonicalSnapshotHash: project.snapshotHash, sourceFingerprint, materials, files: names.map((path) => ({ path, sha256: fileHashChunked(resolve(root, path)), bytes: statSync(resolve(root, path)).size })) };
  writeJson(resolve(root, "snapshot.json"), record);
  for (const file of record.files) chmodSync(resolve(root, file.path), 0o444);
  return { root, record, markdown: resolve(root, "book.md"), diagrams, diagramCount: assembled.diagramCount };
}
export function verifySnapshot(project, snapshot, tools) { if (materialHash(snapshotMaterials(project, tools)) !== snapshot.record.sourceFingerprint) throw new Error("Canonical source, policy, configuration, or tool drifted during release build."); for (const file of snapshot.record.files) if (fileHashChunked(resolve(snapshot.root, file.path)) !== file.sha256) throw new Error(`Prepared release snapshot drifted: ${file.path}`); return true; }
