import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import test from "node:test";
import Ajv2020 from "ajv/dist/2020.js";
import { createCandidate, verifyCandidate } from "../scripts/publishing/candidate.mjs";
import { fileHash, writeJson } from "../scripts/publishing/common.mjs";
import { createManifest, verifyManifest } from "../scripts/publishing/manifest.mjs";
import { verifyReleaseDirectory } from "../scripts/publishing/verify-release.mjs";
import { registerReleaseCandidate, reserveReleaseIdentity } from "../scripts/publishing/release-registry.mjs";
import { ReleaseReviewService } from "../scripts/publishing/release-review-service.mjs";
import { CanonicalLifecycleBindingProvider } from "../scripts/lifecycle/bindings.mjs";
import { LifecycleService } from "../scripts/lifecycle/service.mjs";
import { loadPublishApproval } from "../scripts/publishing/approval-store.mjs";
import { assertSafeMarkup } from "../scripts/publishing/verify.mjs";

test("SEC-004 rejects active markup and unsafe URLs while permitting inert task boxes", () => { assert.throws(() => assertSafeMarkup('<img src="x" onerror="alert(1)">', "HTML"), /security/); assert.throws(() => assertSafeMarkup('<a href="javascript:alert(1)">bad</a>', "EPUB"), /security/); assert.doesNotThrow(() => assertSafeMarkup('<input type="checkbox"></input>', "HTML")); });

function releaseFixture(lifecycleVersion = 4) { const root = mkdtempSync(resolve(tmpdir(), "rtb-release-")), artifacts = {}; for (const [format, name] of [["html", "book.html"], ["pdf", "book.pdf"], ["epub", "book.epub"]]) { const file = resolve(root, name); writeFileSync(file, `${format}-artifact`); artifacts[format] = { path: name, mediaType: "test/fixture", bytes: Buffer.byteLength(`${format}-artifact`), sha256: fileHash(file) }; } const bundleDirectory = resolve(root, "source-snapshot"); mkdirSync(bundleDirectory); writeFileSync(resolve(bundleDirectory, "book.md"), "# Source\n"); const snapshot = { hash: "b".repeat(64), repository: { revision: "c".repeat(40), tree: "d".repeat(40) }, bundle: { path: "source-snapshot", files: [{ path: "book.md", sha256: fileHash(resolve(bundleDirectory, "book.md")), bytes: 9 }] } }, verification = { sourceFingerprint: "a".repeat(64), status: "passed", semanticParity: { status: "passed" }, pdf: { vera: { "2a": { compliant: true }, ua1: { compliant: true } } }, artifacts }; const candidate = createCandidate({ projectId: "generic-consulting-book", lifecycleVersion, sourceFingerprint: "a".repeat(64), snapshot, verification, policies: { releaseEligible: true } }); writeJson(resolve(root, "candidate.json"), candidate); writeJson(resolve(root, "verification.json"), verification); return { root, candidate, snapshot, dispose: () => rmSync(root, { recursive: true, force: true }) }; }
test("PUB/REL candidate is deterministic, provider-neutral, and fails closed on drift", () => { const item = releaseFixture(); try { assert.equal(verifyCandidate(item.candidate), true); const duplicate = createCandidate({ projectId: item.candidate.projectId, lifecycleVersion: 4, sourceFingerprint: "a".repeat(64), snapshot: item.snapshot, verification: { status: "passed", semanticParity: { status: "passed" }, pdf: item.candidate.validators.pdf, artifacts: item.candidate.artifacts }, policies: { releaseEligible: true } }); assert.equal(duplicate.candidateHash, item.candidate.candidateHash); assert.match(item.candidate.futureStaging.reference, /^future-staging:/); assert.equal(item.candidate.futureStaging.activated, false); const changed = structuredClone(item.candidate); changed.artifacts.pdf.sha256 = "0".repeat(64); assert.throws(() => verifyCandidate(changed), /hash/); assert.equal(verifyReleaseDirectory(item.root, item.candidate), true); writeFileSync(resolve(item.root, "candidate.json"), "{\"tampered\":true}\n"); assert.throws(() => verifyReleaseDirectory(item.root, item.candidate), /candidate.json/); writeJson(resolve(item.root, "candidate.json"), item.candidate); writeFileSync(resolve(item.root, "unexpected.bin"), "x"); assert.throws(() => verifyReleaseDirectory(item.root, item.candidate), /extra/); } finally { item.dispose(); } });
test("REL manifest requires exact approval and permanently consumes its release identity", () => { const item = releaseFixture(); try { assert.throws(() => createManifest(item.candidate, null), /human Publish/); const approval = { id: "APR-PUBLISH-1", gate: "publish", decision: "approved", actor: { type: "human", id: "creator" }, explicitConfirmation: true, candidateHash: item.candidate.candidateHash, lifecycleVersion: 4 }; const manifest = createManifest(item.candidate, approval); const ajv = new Ajv2020({ strict: false }); assert.equal(ajv.compile(JSON.parse(readFileSync(resolve("schemas/publishing/release-candidate.schema.json"), "utf8")))(item.candidate), true); assert.equal(ajv.compile(JSON.parse(readFileSync(resolve("schemas/publishing/release-manifest.schema.json"), "utf8")))(manifest), true); assert.equal(verifyManifest(manifest, item.candidate, approval), true); assert.equal(verifyManifest(manifest, item.candidate, manifest.approval), true, "a stored manifest retains its release-policy binding"); assert.equal(manifest.hostedState.activated, false); assert.equal(reserveReleaseIdentity(item.root, manifest), manifest.releaseId); assert.throws(() => reserveReleaseIdentity(item.root, manifest), /already consumed/); assert.throws(() => createManifest(item.candidate, { ...approval, candidateHash: "f".repeat(64) }), /stale/); } finally { item.dispose(); } });
test("real lifecycle services bind Beta and Publish approvals to the exact candidate", async () => { const item = releaseFixture(2); try { writeFileSync(resolve(item.root, "book.md"), "# Fixture\n"); writeFileSync(resolve(item.root, "blueprint.yaml"), "fixture: true\n"); const book = { id: item.candidate.projectId, root: item.root, legacyRoot: item.root, metadataPath: resolve(item.root, "book.md"), manifest: { blueprint: { path: "blueprint.yaml" } }, blueprint: { source_policy: {}, budgets: {}, provider_egress_policy: {} } }, provider = new CanonicalLifecycleBindingProvider({ book }), service = new LifecycleService({ root: item.root, projectId: book.id, bindingProvider: provider }); assert.equal((await service.approve({ gate: "blueprint", expectedVersion: 0, actor: { type: "human", id: "creator" }, explicitConfirmation: true })).state, "succeeded"); provider.registerBeta({ betaSnapshotHash: "b".repeat(64), policyResultsHash: "c".repeat(64), reviewerId: "creator" }); assert.equal((await service.approve({ gate: "beta", expectedVersion: 1, actor: { type: "human", id: "creator" }, explicitConfirmation: true })).state, "succeeded"); registerReleaseCandidate(item.root, item.candidate); const reviews = new ReleaseReviewService({ root: item.root, projectId: book.id, actorResolver: () => ({ type: "human", id: "creator" }) }); reviews.record({ kind: "migration-visual-review", decision: "approved" }); reviews.record({ kind: "pdf-screen-reader-visual-review", decision: "approved" }); reviews.record({ kind: "rights-and-brand-review", decision: "approved", qualifiedRole: "publishing rights owner" }); const published = await service.approve({ gate: "publish", expectedVersion: 2, actor: { type: "human", id: "creator" }, explicitConfirmation: true }); assert.equal(published.state, "succeeded"); const stored = loadPublishApproval(item.root, published.approval.id, item.candidate); assert.equal(stored.candidateHash, item.candidate.candidateHash); assert.equal(stored.lifecycleVersion, 2); assert.equal(stored.approvalLifecycleVersion, 3); } finally { item.dispose(); } });
