import assert from "node:assert/strict";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import test from "node:test";
import { createPromotionCoordinator } from "../scripts/publishing/promotion-state.mjs";
import { acquireProjectLock, acquireWorkspaceOutputLock } from "../scripts/state/project-lock.mjs";

const TOKEN = "11111111-1111-4111-8111-111111111111";
async function fixture(suffix = "", { prior = true, hook } = {}) {
  const workspaceRoot = mkdtempSync(resolve(tmpdir(), `rtb-promotion-${suffix}`)), projectRoot = resolve(workspaceRoot, "books", "book"), outputRoot = resolve(workspaceRoot, "dist", "releases", "immutable"); mkdirSync(projectRoot, { recursive: true }); mkdirSync(outputRoot, { recursive: true });
  const workspaceLock = await acquireWorkspaceOutputLock(workspaceRoot), projectLock = await acquireProjectLock(projectRoot), project = { id: "book", legacyRoot: projectRoot, workspaceRoot }, options = { workspaceRoot, projectRoot, project, releaseId: "REL-EXACT", token: TOKEN, workspaceLock, projectLock, hook }, coordinator = createPromotionCoordinator(options), paths = coordinator.paths(); mkdirSync(paths.staging, { recursive: true }); writeFileSync(resolve(paths.staging, "identity"), "new"); if (prior) { mkdirSync(paths.target, { recursive: true }); writeFileSync(resolve(paths.target, "identity"), "prior"); }
  return { workspaceRoot, projectRoot, outputRoot, options, coordinator: createPromotionCoordinator(options), paths, dispose() { projectLock.release(); workspaceLock.release(); rmSync(workspaceRoot, { recursive: true, force: true }); } };
}
function identity(paths) { return existsSync(resolve(paths.target, "identity")) ? readFileSync(resolve(paths.target, "identity"), "utf8") : null; }
function replaceFile(path, value = "successor") { const moved = `${path}.displaced`; renameSync(path, moved); writeFileSync(path, value); return moved; }
function replaceDirectory(path) { const moved = `${path}.displaced`; renameSync(path, moved); mkdirSync(path); writeFileSync(resolve(path, "identity"), "successor"); return moved; }

test("promotion coordinator is the only exported promotion API", async () => {
  const module = await import("../scripts/publishing/promotion-state.mjs"); assert.deepEqual(Object.keys(module), ["createPromotionCoordinator"]); const publicBuild = await import("../scripts/publishing/project-build.mjs"); for (const name of ["authorizePromotion", "beginPromotion", "commitPromotion", "recoverPromotion", "rollbackPromotion"]) assert.equal(name in publicBuild, false);
});

test("verified promotion retains backup until ledger completion; rollback restores prior", async () => {
  let item = await fixture("success-"); try { let state = item.coordinator.begin(); assert.equal(identity(state), "new"); assert.equal(readFileSync(resolve(state.backup, "identity"), "utf8"), "prior"); state = item.coordinator.markMaterialVerified(); state = item.coordinator.markLedgerCompleted(); item.coordinator.commit(); assert.equal(identity(state), "new"); assert.equal(existsSync(state.marker), false); } finally { item.dispose(); }
  item = await fixture("rollback-"); try { item.coordinator.begin(); item.coordinator.rollback(); assert.equal(identity(item.paths), "prior"); assert.equal(existsSync(item.paths.marker), false); } finally { item.dispose(); }
});

test("marker and rename mutation-validation windows reject replacements and preserve successors", async (context) => {
  const cases = [
    ["after-atomic-marker-prepared", "marker", "begin"], ["after-atomic-old-to-backup", "backup", "begin"], ["after-atomic-staging-to-target", "target", "begin"],
    ["after-atomic-target-quarantine", "quarantine", "rollback"], ["after-atomic-backup-restore", "target", "rollback"],
  ];
  for (const [fault, pathName, stage] of cases) await context.test(fault, async () => { let successor; const item = await fixture(`${fault}-`, { hook: (name, state) => { if (name !== fault) return; const path = state[pathName]; successor = pathName === "marker" ? replaceFile(path) : replaceDirectory(path); } }); try { let failure; try { item.coordinator.begin(); if (stage === "rollback") item.coordinator.rollback(); } catch (error) { failure = error; } assert.match(failure?.message ?? "", /identity changed|bytes changed|contents changed/); const active = item.coordinator.paths()[pathName]; assert.equal(pathName === "marker" ? readFileSync(active, "utf8") : readFileSync(resolve(active, "identity"), "utf8"), "successor"); assert.equal(existsSync(successor), true); assert.throws(() => item.coordinator.assertStable()); } finally { item.dispose(); } });
});

test("ensure and removal mutation-validation windows reject successors", async (context) => {
  await context.test("created target parent replacement", async () => { let successor; const item = await fixture("ensure-target-", { prior: false, hook: (name, state) => { if (name === "after-atomic-ensure-target-parent") successor = replaceDirectory(dirname(state.target)); } }); try { assert.throws(() => item.coordinator.begin(), /identity changed|contents changed/); assert.equal(readFileSync(resolve(dirname(item.paths.target), "identity"), "utf8"), "successor"); assert.equal(existsSync(successor), true); } finally { item.dispose(); } });
  await context.test("created marker parent replacement", async () => { let successor; const item = await fixture("ensure-parent-", { prior: false, hook: (name, state) => { if (name === "after-atomic-ensure-marker-parent-prepared") successor = replaceDirectory(dirname(state.marker)); } }); try { assert.throws(() => item.coordinator.begin(), /identity changed|contents changed/); assert.equal(readFileSync(resolve(dirname(item.paths.marker), "identity"), "utf8"), "successor"); assert.equal(existsSync(successor), true); } finally { item.dispose(); } });
  for (const [fault, pathName] of [["after-atomic-backup-cleanup", "backup"], ["after-atomic-marker-cleanup", "marker"]]) await context.test(fault, async () => { const item = await fixture(`${fault}-`, { hook: (name, state) => { if (name !== fault) return; if (pathName === "marker") writeFileSync(state.marker, "successor"); else { mkdirSync(state.backup); writeFileSync(resolve(state.backup, "identity"), "successor"); } } }); try { let failure; try { item.coordinator.begin(); item.coordinator.markMaterialVerified(); item.coordinator.markLedgerCompleted(); item.coordinator.commit(); } catch (error) { failure = error; } assert.match(failure?.message ?? "", /identity changed/); const path = item.coordinator.paths()[pathName]; assert.equal(pathName === "marker" ? readFileSync(path, "utf8") : readFileSync(resolve(path, "identity"), "utf8"), "successor"); } finally { item.dispose(); } });
  await context.test("quarantine cleanup replacement", async () => { const item = await fixture("quarantine-remove-", { hook: (name, state) => { if (name === "after-atomic-quarantine-cleanup") { mkdirSync(state.quarantine); writeFileSync(resolve(state.quarantine, "identity"), "successor"); } } }); try { item.coordinator.begin(); assert.throws(() => item.coordinator.rollback(), /identity changed/); assert.equal(readFileSync(resolve(item.paths.quarantine, "identity"), "utf8"), "successor"); } finally { item.dispose(); } });
  await context.test("staging cleanup replacement", async () => { const item = await fixture("staging-remove-", { hook: (name) => { if (name === "after-marker-prepared") throw new Error("crash"); } }); try { assert.throws(() => item.coordinator.begin(), /crash/); const recovery = createPromotionCoordinator({ ...item.options, hook: (name, state) => { if (name === "after-atomic-staging-cleanup") { mkdirSync(state.staging); writeFileSync(resolve(state.staging, "identity"), "successor"); } } }); assert.throws(() => recovery.recoverPending(), /identity changed/); assert.equal(readFileSync(resolve(item.paths.staging, "identity"), "utf8"), "successor"); } finally { item.dispose(); } });
});

const beginEvents = ["before-marker-prepared", "after-marker-prepared", "before-marker-backup-intent", "after-marker-backup-intent", "before-old-to-backup", "after-old-to-backup", "before-marker-backup-complete", "after-marker-backup-complete", "before-marker-activate-intent", "after-marker-activate-intent", "before-staging-to-target", "after-staging-to-target", "before-marker-activate-complete", "after-marker-activate-complete"];
const rollbackEvents = ["before-marker-rollback-quarantine-intent", "after-marker-rollback-quarantine-intent", "before-target-quarantine", "after-target-quarantine", "before-marker-rollback-quarantine-complete", "after-marker-rollback-quarantine-complete", "before-marker-rollback-restore-intent", "after-marker-rollback-restore-intent", "before-backup-restore", "after-backup-restore", "before-marker-rollback-restore-complete", "after-marker-rollback-restore-complete", "before-marker-rollback-cleanup-intent", "after-marker-rollback-cleanup-intent", "before-quarantine-cleanup", "after-quarantine-cleanup", "before-marker-rollback-cleanup-complete", "after-marker-rollback-cleanup-complete", "before-marker-cleanup", "after-marker-cleanup"];
const commitEvents = ["before-marker-material-verified", "after-marker-material-verified", "before-marker-ledger-completed", "after-marker-ledger-completed", "before-marker-commit-cleanup-intent", "after-marker-commit-cleanup-intent", "before-backup-cleanup", "after-backup-cleanup", "before-marker-commit-cleanup-complete", "after-marker-commit-cleanup-complete", "before-marker-cleanup", "after-marker-cleanup"];

test("every promotion and rollback crash boundary recovers to the prior release", async (context) => { for (const fault of [...beginEvents, ...rollbackEvents]) await context.test(fault, async () => { const fail = (name) => { if (name === fault) throw new Error(`crash:${fault}`); }, item = await fixture(`${fault}-`, { hook: fail }); try { try { item.coordinator.begin(); item.coordinator.rollback(); } catch {} const recovery = createPromotionCoordinator({ ...item.options, hook: undefined }); recovery.recoverPending({ rollbackCompletionRequired: true }); assert.equal(identity(item.paths), "prior"); assert.equal(existsSync(item.paths.marker), false); } finally { item.dispose(); } }); });

test("verified commit crash boundaries recover to prior or exactly new", async (context) => { for (const fault of commitEvents) await context.test(fault, async () => { const fail = (name) => { if (name === fault) throw new Error(`crash:${fault}`); }, item = await fixture(`commit-${fault}-`, { hook: fail }); try { try { item.coordinator.begin(); item.coordinator.markMaterialVerified(); item.coordinator.markLedgerCompleted(); item.coordinator.commit(); } catch {} const recovery = createPromotionCoordinator({ ...item.options, hook: undefined }); recovery.recoverPending({ rollbackCompletionRequired: true }); assert.equal(["prior", "new"].includes(identity(item.paths)), true); } finally { item.dispose(); } }); });

test("malformed and symbolic marker state fails before mutation", async () => { const item = await fixture("malformed-"); try { mkdirSync(dirname(item.paths.marker), { recursive: true }); writeFileSync(item.paths.marker, JSON.stringify({ schemaVersion: 2, projectId: "book", releaseId: "REL-EXACT", token: TOKEN, phase: "prepared", hadPrior: true })); const recovery = createPromotionCoordinator(item.options); assert.throws(() => recovery.recoverPending(), /malformed or mismatched/); assert.equal(identity(item.paths), "prior"); assert.equal(existsSync(item.paths.staging), true); } finally { item.dispose(); } });
