import assert from "node:assert/strict";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import test from "node:test";
import { assertPromotionTransaction, authorizePromotion, authorizePromotionRecovery, beginPromotion, commitPromotion, markPromotionLedgerCompleted, markPromotionMaterialVerified, pinPromotionTransaction, promotionContext, promotionMarkers, recoverPromotion, rollbackPromotion } from "../scripts/publishing/promotion-state.mjs";
import { acquireProjectLock, acquireWorkspaceOutputLock } from "../scripts/state/project-lock.mjs";

const TOKEN = "11111111-1111-4111-8111-111111111111";
async function fixture(suffix = "", { fast = false } = {}) { const outputRoot = mkdtempSync(resolve(tmpdir(), `rtb-promotion-${suffix}`)), projectRoot = resolve(outputRoot, "project-state"), input = { outputRoot, projectId: "book", releaseId: "REL-EXACT", token: TOKEN, testOnlySkipDurability: fast }, context = promotionContext(input); mkdirSync(projectRoot); mkdirSync(context.target, { recursive: true }); mkdirSync(context.staging, { recursive: true }); writeFileSync(resolve(context.target, "identity"), "prior"); writeFileSync(resolve(context.staging, "identity"), "new"); const workspaceLock = await acquireWorkspaceOutputLock(outputRoot), projectLock = await acquireProjectLock(projectRoot), lockOptions = { workspaceRoot: outputRoot, projectRoot, workspaceLock, projectLock }; return { outputRoot, projectRoot, input, context, lockOptions, dispose: () => { projectLock.release(); workspaceLock.release(); rmSync(outputRoot, { recursive: true, force: true }); } }; }
function identity(context) { return existsSync(resolve(context.target, "identity")) ? readFileSync(resolve(context.target, "identity"), "utf8") : null; }
function recoverAll(item) { for (const context of promotionMarkers(item.input.outputRoot, item.input.projectId, item.input.releaseId, { testOnlySkipDurability: item.input.testOnlySkipDurability })) { const authorized = authorizePromotionRecovery(context, item.lockOptions), recovered = recoverPromotion(context, authorized.authority); if (recovered.state === "completion-required") rollbackPromotion(recovered.context, authorized.authority); } }

test("verified promotion retains backup until durable ledger completion then commits", async () => { const item = await fixture("success-"); try { const authority = authorizePromotion(item.context, item.lockOptions); let state = beginPromotion(item.input, authority); assert.equal(identity(state), "new"); assert.equal(readFileSync(resolve(state.backup, "identity"), "utf8"), "prior"); state = markPromotionMaterialVerified(state, authority); state = markPromotionLedgerCompleted(state, authority); commitPromotion(state, authority); assert.equal(identity(state), "new"); assert.equal(existsSync(state.backup), false); assert.equal(existsSync(state.marker), false); } finally { item.dispose(); } });
test("unverified promotion rollback restores the prior release", async () => { const item = await fixture("rollback-"); try { const authority = authorizePromotion(item.context, item.lockOptions), state = beginPromotion(item.input, authority); rollbackPromotion(state, authority); assert.equal(identity(state), "prior"); assert.equal(existsSync(state.marker), false); } finally { item.dispose(); } });

test("promotion mutators reject direct calls and are not re-exported by project-build", async () => {
  const item = await fixture("direct-authority-"); try { assert.throws(() => beginPromotion(item.input), /branded recovery authority/); assert.equal(identity(item.context), "prior"); assert.equal(existsSync(item.context.staging), true); const publicBuild = await import("../scripts/publishing/project-build.mjs"); for (const name of ["beginPromotion", "commitPromotion", "rollbackPromotion", "recoverPromotion"]) assert.equal(name in publicBuild, false); } finally { item.dispose(); }
});

test("pinned promotion authority rejects state, marker, backup, and quarantine replacement", async (context) => {
  for (const kind of ["state", "marker", "backup"]) await context.test(kind, async () => {
    const item = await fixture(`replace-${kind}-`); try { const mutationAuthority = authorizePromotion(item.context, item.lockOptions), state = beginPromotion(item.input, mutationAuthority), authority = pinPromotionTransaction(state), path = kind === "state" ? dirname(state.marker) : state[kind], displaced = `${path}.displaced`; renameSync(path, displaced); if (kind === "marker") writeFileSync(path, readFileSync(displaced)); else cpSync(displaced, path, { recursive: true }); assert.throws(() => assertPromotionTransaction(authority), /identity changed|unsafe/); assert.throws(() => rollbackPromotion(state, mutationAuthority), /identity changed|unsafe/); assert.equal(existsSync(displaced), true); } finally { item.dispose(); }
  });
  await context.test("quarantine", async () => {
    const item = await fixture("replace-quarantine-"); try { const mutationAuthority = authorizePromotion(item.context, item.lockOptions); let error; try { const state = beginPromotion(item.input, mutationAuthority); rollbackPromotion(state, mutationAuthority, (name) => { if (name === "after-marker-rollback-quarantine-complete") throw new Error("stop"); }); } catch (caught) { error = caught; } const state = error.promotionContext, authority = error.promotionTransactionAuthority, displaced = `${state.quarantine}.displaced`; renameSync(state.quarantine, displaced); cpSync(displaced, state.quarantine, { recursive: true }); assert.throws(() => assertPromotionTransaction(authority), /identity changed|unsafe/); assert.throws(() => rollbackPromotion(state, mutationAuthority), /identity changed|unsafe/); assert.equal(existsSync(displaced), true); } finally { item.dispose(); }
  });
});

const beginEvents = ["before-marker-prepared", "after-marker-prepared", "before-marker-backup-intent", "after-marker-backup-intent", "before-old-to-backup", "after-old-to-backup", "before-marker-backup-complete", "after-marker-backup-complete", "before-marker-activate-intent", "after-marker-activate-intent", "before-staging-to-target", "after-staging-to-target", "before-marker-activate-complete", "after-marker-activate-complete"];
const rollbackEvents = ["before-marker-rollback-quarantine-intent", "after-marker-rollback-quarantine-intent", "before-target-quarantine", "after-target-quarantine", "before-marker-rollback-quarantine-complete", "after-marker-rollback-quarantine-complete", "before-marker-rollback-restore-intent", "after-marker-rollback-restore-intent", "before-backup-restore", "after-backup-restore", "before-marker-rollback-restore-complete", "after-marker-rollback-restore-complete", "before-marker-rollback-cleanup-intent", "after-marker-rollback-cleanup-intent", "before-quarantine-cleanup", "after-quarantine-cleanup", "before-marker-rollback-cleanup-complete", "after-marker-rollback-cleanup-complete", "before-marker-cleanup", "after-marker-cleanup"];
const commitEvents = ["before-marker-material-verified", "after-marker-material-verified", "before-marker-ledger-completed", "after-marker-ledger-completed", "before-marker-commit-cleanup-intent", "after-marker-commit-cleanup-intent", "before-backup-cleanup", "after-backup-cleanup", "before-marker-commit-cleanup-complete", "after-marker-commit-cleanup-complete", "before-marker-cleanup", "after-marker-cleanup"];

test("every promotion and rollback crash boundary recovers to the prior verified release", async (context) => {
  for (const fault of [...beginEvents, "before-verification", "after-verification", ...rollbackEvents]) await context.test(fault, async () => { const item = await fixture(`${fault}-`, { fast: true }); try { const fail = (name) => { if (name === fault) throw new Error(`crash:${fault}`); }, authority = authorizePromotion(item.context, item.lockOptions); let state; try { state = beginPromotion(item.input, authority, fail); if (fault === "before-verification" || fault === "after-verification") throw new Error(`crash:${fault}`); rollbackPromotion(state, authority, fail); } catch {} recoverAll(item); assert.equal(identity(item.context), "prior"); assert.equal(promotionMarkers(item.outputRoot, "book", "REL-EXACT").length, 0); } finally { item.dispose(); } });
});

test("every verified-commit crash boundary recovers to prior or exactly completed new release", async (context) => {
  for (const fault of commitEvents) await context.test(fault, async () => { const item = await fixture(`commit-${fault}-`, { fast: true }); try { const fail = (name) => { if (name === fault) throw new Error(`crash:${fault}`); }, authority = authorizePromotion(item.context, item.lockOptions); let state = beginPromotion(item.input, authority); try { state = markPromotionMaterialVerified(state, authority, fail); state = markPromotionLedgerCompleted(state, authority, fail); commitPromotion(state, authority, fail); } catch {} recoverAll(item); const value = identity(item.context); assert.equal(["prior", "new"].includes(value), true); if (value === "new") { assert.equal(existsSync(item.context.backup), false); assert.equal(existsSync(item.context.quarantine), false); } } finally { item.dispose(); } });
});

test("malformed, mismatched, traversal, and symbolic-link markers fail without mutation", async (context) => {
  const corruptions = {
    "extra path": (marker) => ({ ...marker, target: "/tmp/attacker" }), "wrong schema": (marker) => ({ ...marker, schemaVersion: 2 }), "unknown phase": (marker) => ({ ...marker, phase: "trust-new" }), "wrong project": (marker) => ({ ...marker, projectId: "other" }), "wrong release": (marker) => ({ ...marker, releaseId: "REL-OTHER" }), "wrong token": (marker) => ({ ...marker, token: "22222222-2222-4222-8222-222222222222" }), "missing field": ({ phase: _phase, ...marker }) => marker,
  };
  for (const [name, corrupt] of Object.entries(corruptions)) await context.test(name, async () => { const item = await fixture(`malicious-${name}-`); try { mkdirSync(dirname(item.context.marker), { recursive: true }); const marker = { schemaVersion: 1, projectId: "book", releaseId: "REL-EXACT", token: TOKEN, phase: "prepared", hadPrior: true }; writeFileSync(item.context.marker, JSON.stringify(corrupt(marker))); assert.throws(() => authorizePromotionRecovery(item.context, item.lockOptions), /malformed or mismatched/); assert.equal(identity(item.context), "prior"); assert.equal(existsSync(item.context.staging), true); } finally { item.dispose(); } });
  await context.test("invalid JSON", async () => { const item = await fixture("malicious-json-"); try { mkdirSync(dirname(item.context.marker), { recursive: true }); writeFileSync(item.context.marker, "{not-json"); assert.throws(() => authorizePromotionRecovery(item.context, item.lockOptions)); assert.equal(identity(item.context), "prior"); assert.equal(existsSync(item.context.staging), true); } finally { item.dispose(); } });
  assert.throws(() => promotionContext({ outputRoot: "/tmp", projectId: "../escape", releaseId: "REL-X", token: TOKEN }), /safe project/);
  await context.test("marker symlink", async () => { const item = await fixture("marker-link-"); try { mkdirSync(dirname(item.context.marker), { recursive: true }); const outside = resolve(item.outputRoot, "outside.json"); writeFileSync(outside, "{}"); symlinkSync(outside, item.context.marker); assert.throws(() => authorizePromotionRecovery(item.context, item.lockOptions), /symbolic links/); assert.equal(identity(item.context), "prior"); } finally { item.dispose(); } });
  for (const kind of ["backup", "quarantine"]) await context.test(`${kind} replacement before retry pin`, async () => { const item = await fixture(`${kind}-pre-pin-`); try { mkdirSync(dirname(item.context.marker), { recursive: true }); writeFileSync(item.context.marker, `${JSON.stringify({ schemaVersion: 1, projectId: "book", releaseId: "REL-EXACT", token: TOKEN, phase: "prepared", hadPrior: true })}\n`); const outside = resolve(item.outputRoot, `${kind}-successor`); mkdirSync(outside); writeFileSync(resolve(outside, "identity"), "successor"); symlinkSync(outside, item.context[kind]); assert.throws(() => authorizePromotionRecovery(item.context, item.lockOptions), /symbolic links/); assert.equal(readFileSync(resolve(outside, "identity"), "utf8"), "successor"); assert.equal(identity(item.context), "prior"); } finally { item.dispose(); } });
});
