CREATE TABLE IF NOT EXISTS lifecycle_transitions (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, expected_version INTEGER NOT NULL, prior_state TEXT NOT NULL, requested_state TEXT NOT NULL, resulting_version INTEGER NOT NULL, actor_type TEXT NOT NULL, actor_id TEXT NOT NULL, reason TEXT NOT NULL, guard_results_json TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(project_id, resulting_version));
CREATE TRIGGER IF NOT EXISTS lifecycle_transitions_append_only_update BEFORE UPDATE ON lifecycle_transitions BEGIN SELECT RAISE(ABORT, 'lifecycle transitions are append-only'); END;
CREATE TRIGGER IF NOT EXISTS lifecycle_transitions_append_only_delete BEFORE DELETE ON lifecycle_transitions BEGIN SELECT RAISE(ABORT, 'lifecycle transitions are append-only'); END;
CREATE TABLE IF NOT EXISTS lifecycle_approvals (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, gate TEXT NOT NULL, decision TEXT NOT NULL, actor_type TEXT NOT NULL, actor_id TEXT NOT NULL, explicit_confirmation INTEGER NOT NULL, lifecycle_version INTEGER NOT NULL, bindings_json TEXT NOT NULL, expires_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS lifecycle_approval_invalidations (id TEXT PRIMARY KEY, approval_id TEXT NOT NULL, project_id TEXT NOT NULL, reason TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(approval_id));
CREATE TABLE IF NOT EXISTS workflow_runs (run_id TEXT PRIMARY KEY, project_id TEXT NOT NULL, operation_kind TEXT NOT NULL, idempotency_key TEXT NOT NULL, input_fingerprint TEXT NOT NULL, status TEXT NOT NULL, visible_state TEXT NOT NULL, cancellation_requested_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(project_id, operation_kind, idempotency_key));
CREATE TABLE IF NOT EXISTS workflow_stages (stage_id TEXT PRIMARY KEY, run_id TEXT NOT NULL, stage_kind TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(run_id, stage_kind));
CREATE TABLE IF NOT EXISTS workflow_attempts (attempt_id TEXT PRIMARY KEY, stage_id TEXT NOT NULL, parent_attempt_id TEXT, attempt_number INTEGER NOT NULL, owner_id TEXT, heartbeat_at TEXT, status TEXT NOT NULL, visible_state TEXT NOT NULL, retry_class TEXT, checkpoint_json TEXT, failure_message TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(stage_id, attempt_number));
CREATE TABLE IF NOT EXISTS workflow_dispatches (id TEXT PRIMARY KEY, attempt_id TEXT NOT NULL, destination TEXT NOT NULL, operation TEXT NOT NULL, idempotency_key TEXT NOT NULL, input_fingerprint TEXT NOT NULL, status TEXT NOT NULL, external_identity TEXT, outcome_json TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(attempt_id, destination, operation));
