import { openStateDatabase, durableCheckpoint } from "../state/database.mjs";
import { id, timestamp } from "./model.mjs";
const state = (s, r) => ({ queued: "queued", running: "running", succeeded: "succeeded", cancelled: "cancelled", stale: "stale", failed: r === "retryable" ? "failed-retryable" : r === "blocked-awaiting-action" ? "blocked" : "failed-terminal" }[s] ?? "failed-terminal");
export class WorkflowLedger {
  constructor({ file, now = () => Date.now() } = {}) { this.file = file; this.now = now; }
  db() { return openStateDatabase(this.file, { now: this.now }); }
  attempt(db, runId) { return db.prepare("SELECT r.*,s.stage_id,a.attempt_id,a.parent_attempt_id,a.attempt_number,a.owner_id,a.fencing_token,a.status AS attempt_status,a.visible_state AS attempt_visible_state,a.retry_class,a.retry_limit FROM workflow_runs r JOIN workflow_stages s ON s.run_id=r.run_id JOIN workflow_attempts a ON a.stage_id=s.stage_id WHERE r.run_id=? ORDER BY a.attempt_number DESC LIMIT 1").get(runId); }
  submit({ projectId, operationKind, idempotencyKey, inputFingerprint, retryLimit = 2 } = {}) { const db = this.db(), now = timestamp(this.now); try { db.exec("BEGIN IMMEDIATE"); const old = db.prepare("SELECT * FROM workflow_runs WHERE project_id=? AND operation_kind=? AND idempotency_key=?").get(projectId, operationKind, idempotencyKey); if (old) { db.exec("COMMIT"); return old.input_fingerprint === inputFingerprint ? { state: old.visible_state, created: false, runId: old.run_id, attempt: this.attempt(db, old.run_id) } : { state: "conflict", runId: old.run_id }; } const runId=id("RUN"), stageId=id("STG"), attemptId=id("ATT"); db.prepare("INSERT INTO workflow_runs VALUES (?,?,?,?,?,'queued','queued',NULL,?,?)").run(runId,projectId,operationKind,idempotencyKey,inputFingerprint,now,now); db.prepare("INSERT INTO workflow_stages VALUES (?,?,?,'queued',?,?)").run(stageId,runId,"execute",now,now); db.prepare("INSERT INTO workflow_attempts (attempt_id,stage_id,attempt_number,status,visible_state,retry_limit,progress_json,created_at,updated_at) VALUES (?,?,1,'queued','queued',?,'{}',?,?)").run(attemptId,stageId,retryLimit,now,now); db.exec("COMMIT"); durableCheckpoint(db); return { state:"queued",created:true,runId,attempt:this.attempt(db,runId) }; } finally { db.close(); } }
  claim(runId, ownerId) { const db=this.db(),now=timestamp(this.now); try { db.exec("BEGIN IMMEDIATE"); const a=this.attempt(db,runId); if (!a || a.attempt_status!=="queued") { db.exec("COMMIT"); return null; } const fence=a.fencing_token+1; const n=db.prepare("UPDATE workflow_attempts SET status='running',visible_state='running',owner_id=?,fencing_token=?,heartbeat_at=?,updated_at=? WHERE attempt_id=? AND status='queued' AND fencing_token=?").run(ownerId,fence,now,now,a.attempt_id,a.fencing_token).changes; if(!n){db.exec("COMMIT");return null;} db.prepare("UPDATE workflow_runs SET status='running',visible_state='running',updated_at=? WHERE run_id=?").run(now,runId); db.exec("COMMIT"); return { ...this.attempt(db,runId), ownerId, fencingToken:fence }; } finally { db.close(); } }
  heartbeat(attemptId,owner,fence){const db=this.db();try{return db.prepare("UPDATE workflow_attempts SET heartbeat_at=?,updated_at=? WHERE attempt_id=? AND owner_id=? AND fencing_token=? AND status='running'").run(timestamp(this.now),timestamp(this.now),attemptId,owner,fence).changes===1;}finally{db.close();}}
  finish(attemptId,owner,fence,{status,retryClass=null,message=null}={}){const db=this.db(),now=timestamp(this.now);try{db.exec("BEGIN IMMEDIATE");const row=db.prepare("SELECT s.run_id FROM workflow_attempts a JOIN workflow_stages s ON s.stage_id=a.stage_id WHERE a.attempt_id=? AND a.owner_id=? AND a.fencing_token=? AND a.status='running'").get(attemptId,owner,fence);if(!row)throw new Error("Workflow attempt owner fence rejected completion.");const visible=state(status,retryClass);db.prepare("UPDATE workflow_attempts SET status=?,visible_state=?,retry_class=?,failure_message=?,updated_at=? WHERE attempt_id=?").run(status,visible,retryClass,message,now,attemptId);db.prepare("UPDATE workflow_runs SET status=?,visible_state=?,updated_at=? WHERE run_id=?").run(status,visible,now,row.run_id);db.exec("COMMIT");return this.get(row.run_id);}finally{db.close();}}
  cancel(runId){const db=this.db(),now=timestamp(this.now);try{db.exec("BEGIN IMMEDIATE");const a=this.attempt(db,runId);if(!a||!["queued","running"].includes(a.attempt_status)){db.exec("COMMIT");return false;}db.prepare("UPDATE workflow_attempts SET status='cancelled',visible_state='cancelled',retry_class='cancelled',updated_at=? WHERE attempt_id=?").run(now,a.attempt_id);db.prepare("UPDATE workflow_runs SET status='cancelled',visible_state='cancelled',cancellation_requested_at=?,updated_at=? WHERE run_id=?").run(now,now,runId);db.exec("COMMIT");return true;}finally{db.close();}}
  retry(runId){const db=this.db(),now=timestamp(this.now);try{db.exec("BEGIN IMMEDIATE");const a=this.attempt(db,runId);if(!a||!((a.attempt_status==='failed'&&a.retry_class==='retryable')||a.attempt_status==='stale')||a.attempt_number>=a.retry_limit)throw new Error("Only a retryable failed or recovered stale attempt may be retried.");if(db.prepare("SELECT 1 FROM workflow_dispatches WHERE attempt_id=?").get(a.attempt_id))throw new Error("A dispatched external side effect requires reconciliation and cannot be retried automatically.");const next=id("ATT");db.prepare("INSERT INTO workflow_attempts (attempt_id,stage_id,parent_attempt_id,attempt_number,status,visible_state,retry_limit,progress_json,created_at,updated_at) VALUES (?,?,?,?,'queued','queued',?,'{}',?,?)").run(next,a.stage_id,a.attempt_id,a.attempt_number+1,a.retry_limit,now,now);db.prepare("UPDATE workflow_runs SET status='queued',visible_state='queued',updated_at=? WHERE run_id=?").run(now,runId);db.exec("COMMIT");return {state:'queued',runId,attempt:this.attempt(db,runId)};}finally{db.close();}}
  dispatch(attemptId,owner,fence,{destination,operation,idempotencyKey,inputFingerprint}){const db=this.db(),now=timestamp(this.now);try{db.exec("BEGIN IMMEDIATE");if(!db.prepare("SELECT 1 FROM workflow_attempts WHERE attempt_id=? AND owner_id=? AND fencing_token=? AND status='running'").get(attemptId,owner,fence))throw new Error("Workflow attempt owner fence rejected dispatch.");const e=db.prepare("SELECT status FROM workflow_dispatches WHERE attempt_id=? AND destination=? AND operation=?").get(attemptId,destination,operation);if(e){db.exec("COMMIT");return{safeToSend:false,reason:e.status};}db.prepare("INSERT INTO workflow_dispatches (id,attempt_id,destination,operation,idempotency_key,input_fingerprint,status,owner_id,fencing_token,created_at,updated_at) VALUES (?,?,?,?,?,?,'pending',?,?,?,?)").run(id('DSP'),attemptId,destination,operation,idempotencyKey,inputFingerprint,owner,fence,now,now);db.exec("COMMIT");return{safeToSend:true};}finally{db.close();}}
  completeDispatch(attemptId,owner,fence,{destination,operation,externalIdentity}){const db=this.db();try{const n=db.prepare("UPDATE workflow_dispatches SET status='completed',external_identity=?,updated_at=? WHERE attempt_id=? AND destination=? AND operation=? AND status='pending' AND owner_id=? AND fencing_token=?").run(externalIdentity??null,timestamp(this.now),attemptId,destination,operation,owner,fence).changes;if(n!==1)throw new Error("Workflow attempt owner fence rejected dispatch completion.");}finally{db.close();}}
  recoverStale({olderThanMs=60000}={}){const db=this.db(),cutoff=new Date(this.now()-olderThanMs).toISOString(),now=timestamp(this.now);try{db.exec("BEGIN IMMEDIATE");const rows=db.prepare("SELECT a.attempt_id,s.run_id FROM workflow_attempts a JOIN workflow_stages s ON s.stage_id=a.stage_id WHERE a.status='running' AND (a.heartbeat_at IS NULL OR a.heartbeat_at < ?)").all(cutoff);for(const r of rows){db.prepare("UPDATE workflow_attempts SET status='stale',visible_state='stale',retry_class='retryable',owner_id=NULL,fencing_token=fencing_token+1,updated_at=? WHERE attempt_id=?").run(now,r.attempt_id);db.prepare("UPDATE workflow_runs SET status='stale',visible_state='stale',updated_at=? WHERE run_id=?").run(now,r.run_id);}db.exec("COMMIT");return rows.map(x=>x.run_id);}finally{db.close();}}
  get(runId){const db=this.db();try{return db.prepare("SELECT * FROM workflow_runs WHERE run_id=?").get(runId);}finally{db.close();}}
}
