import { resolve } from "node:path";
import { ROOT } from "../lib.mjs";

export const SCHEMA_VERSION = 1;
export const GENERATOR_VERSION = "1";
export const DEFAULT_MANIFEST = "rtb-publishing.project.yaml";
export const SCHEMA_FILE = resolve(ROOT, "schemas", "rtb-publishing.project.schema.json");
export const TEMPLATE_DIRECTORY = resolve(ROOT, "templates", "engineering-kit");
export const STATE_DIRECTORY = ".rtb-publishing";
export const STATE_FILE = "generation-state.json";
export const GENERATED_MARKER = "<!-- Generated by RTB Publishing. Source: rtb-publishing.project.yaml. -->";

export const TEMPLATE_OUTPUTS = Object.freeze({
  "README.md.tpl": "README.md",
  "vision-manifesto.md.tpl": "docs/strategy/vision-manifesto.md",
  "worthiness-review.md.tpl": "docs/strategy/worthiness-review.md",
  "product-requirements.md.tpl": "docs/strategy/product-requirements.md",
  "ADR-000-foundational-architecture.md.tpl": "governance/ADR/ADR-000-foundational-architecture.md",
  "MILESTONES.md.tpl": "planning/MILESTONES.md",
  "verification-plan.md.tpl": "planning/verification-plan.md",
  "CHANGELOG.md.tpl": "CHANGELOG.md"
});
