import { closeSync, existsSync, fsyncSync, lstatSync, openSync, readFileSync, readdirSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { createHash, randomUUID } from "node:crypto";
import { basename, delimiter, dirname, relative, resolve, sep } from "node:path";
import { DIST_DIR, ROOT, run } from "./lib.mjs";
import { assembleBook, projectOutputPath } from "./books/assemble.mjs";
import { assertCurrentProjectIdentity, pinnedProjectCanonicalHash, resolveBookProject } from "./books/discovery.mjs";
import { verifyOutputs } from "./verify-outputs.mjs";
import { buildRelease } from "./publishing/project-build.mjs";
import { acquireProjectLockImmediate, acquireWorkspaceOutputLockImmediate, assertNoSymlinkPath, assertPinnedEntry, ensurePhysicalDirectory, pinPhysicalDirectory, pinPhysicalEntry } from "./state/project-lock.mjs";
export { buildRelease };
function syncPath(path, kind, hooks) { hooks.durability?.(`before-fsync-${kind}`, path); const fd = openSync(path, "r"); try { fsyncSync(fd); } finally { closeSync(fd); } hooks.durability?.(`after-fsync-${kind}`, path); }
function syncGenerationTree(root, hooks) { const directories = []; const walk = (directory) => { directories.push(directory); for (const name of readdirSync(directory).sort()) { const path = resolve(directory, name), entry = lstatSync(path); if (entry.isSymbolicLink()) throw new Error(`Generic build generation contains a symbolic link: ${path}`); if (entry.isDirectory()) walk(path); else if (entry.isFile() && entry.nlink === 1) syncPath(path, "file", hooks); else throw new Error(`Generic build generation contains a non-private file: ${path}`); } }; walk(root); for (const directory of directories.reverse()) syncPath(directory, "directory", hooks); }
function treeRecord(path) { const entry = lstatSync(path); if (entry.isSymbolicLink()) throw new Error(`Generic generation tree contains a symbolic link: ${path}`); if (entry.isFile()) { if (entry.nlink !== 1) throw new Error(`Generic generation tree contains a non-private file: ${path}`); return { path, type: "file", dev: entry.dev, ino: entry.ino, size: entry.size, hash: createHash("sha256").update(readFileSync(path)).digest("hex") }; } if (!entry.isDirectory()) throw new Error(`Generic generation tree contains an unsafe entry: ${path}`); return { path, type: "directory", dev: entry.dev, ino: entry.ino, children: readdirSync(path).sort().map((name) => treeRecord(resolve(path, name))) }; }
function assertTree(record, at = record.path) { const entry = lstatSync(at); if (entry.isSymbolicLink() || record.type === "file" && (!entry.isFile() || entry.nlink !== 1) || record.type === "directory" && !entry.isDirectory() || entry.dev !== record.dev || entry.ino !== record.ino) throw new Error(`Generic generation tree identity changed: ${at}`); if (record.type === "file") { if (entry.size !== record.size || createHash("sha256").update(readFileSync(at)).digest("hex") !== record.hash) throw new Error(`Generic generation tree bytes changed: ${at}`); return; } const names = readdirSync(at).sort(); if (names.length !== record.children.length) throw new Error(`Generic generation tree contents changed: ${at}`); for (let index = 0; index < names.length; index += 1) { if (basename(record.children[index].path) !== names[index]) throw new Error(`Generic generation tree contents changed: ${at}`); assertTree(record.children[index], resolve(at, names[index])); } }
function collectGenerations(root, current) { if (!existsSync(root)) return []; return readdirSync(root).map((name) => { const path = resolve(root, name), entry = lstatSync(path); if (entry.isSymbolicLink() || !entry.isDirectory()) throw new Error(`Generic generation retention found an unsafe entry: ${path}`); return { name, path, modified: statSync(path).mtimeMs, current: name === current }; }).sort((left, right) => right.modified - left.modified || right.name.localeCompare(left.name)); }
function readPointer(pointer, projectId) { const bytes = readFileSync(pointer), value = JSON.parse(bytes.toString("utf8")); if (value.schemaVersion !== 1 || value.projectId !== projectId || typeof value.generation !== "string") throw new Error("Generic generation retention found an invalid current pointer."); return { bytes, generation: value.generation }; }
function retainGenerations(outputRoot, root, pointer, projectId, hooks) { const initial = readPointer(pointer, projectId), pointerRecord = treeRecord(pointer), pointerChanged = () => new Error("Current generation pointer changed during retention; no generation was deleted."), assertPointer = () => { try { assertTree(pointerRecord); } catch { throw pointerChanged(); } const current = readPointer(pointer, projectId); if (!current.bytes.equals(initial.bytes) || current.generation !== initial.generation) throw pointerChanged(); }, generations = collectGenerations(root, initial.generation), keep = new Set([initial.generation, ...generations.filter((item) => !item.current).slice(0, 2).map((item) => item.name)]), removals = generations.filter((item) => !keep.has(item.name)).map((item) => ({ ...item, record: treeRecord(item.path) })); if (!removals.length) return; const quarantine = resolve(outputRoot, ".gc", projectId, randomUUID()), moved = []; ensurePhysicalDirectory(outputRoot, quarantine); try { for (const item of removals) { hooks.beforeGenerationGc?.({ generation: item.name, path: item.path, moved: moved.length }); assertPointer(); assertTree(item.record); const destination = resolve(quarantine, item.name); if (existsSync(destination)) throw new Error("Generation retention quarantine collision."); renameSync(item.path, destination); syncPath(root, "generation-gc-source-parent", hooks); syncPath(quarantine, "generation-gc-destination-parent", hooks); assertTree(item.record, destination); moved.push({ ...item, destination }); } assertPointer(); for (const item of moved) rmSync(item.destination, { recursive: true }); syncPath(quarantine, "generation-gc-parent", hooks); hooks.afterGenerationGc?.({ removed: moved.map((item) => item.name) }); } catch (error) { for (const item of [...moved].reverse()) if (existsSync(item.destination) && !existsSync(item.path)) renameSync(item.destination, item.path); syncPath(root, "generation-gc-restore-parent", hooks); throw error; } finally { rmSync(resolve(outputRoot, ".gc"), { recursive: true, force: true }); } }

export function outputDispatch(project) {
  return project.outputProfiles.map((profile) => {
    if (!["html", "epub", "pdf"].includes(profile.format)) throw new Error(`Unsupported declared output format: ${profile.format}.`);
    return profile;
  });
}
export function buildProject(project, { outputRoot = resolve(DIST_DIR, "books"), workspaceRoot = project.workspaceRoot ?? ROOT, hooks = {} } = {}) {
  const requested = project, logicalWorkspace = resolve(workspaceRoot), workspace = pinPhysicalDirectory(workspaceRoot).path;
  const physicalize = (path) => {
    const requestedPath = resolve(path), value = relative(logicalWorkspace, requestedPath);
    if (value !== ".." && !value.startsWith(`..${sep}`)) return resolve(workspace, value);
    let ancestor = requestedPath;
    while (!existsSync(ancestor)) { const parent = dirname(ancestor); if (parent === ancestor) throw new Error(`Cannot establish a physical output root for ${requestedPath}.`); ancestor = parent; }
    const authority = pinPhysicalDirectory(ancestor).path, physicalPath = resolve(authority, relative(ancestor, requestedPath));
    assertNoSymlinkPath(authority, physicalPath);
    return physicalPath;
  };
  const physicalOutputRoot = physicalize(outputRoot), workspaceLock = acquireWorkspaceOutputLockImmediate(workspace, { ownerId: `book-build-output-${process.pid}` });
  let lock;
  const token = randomUUID(); let buildDirectory, outputDirectory, stagingGeneration, stagingBuild, stagingOutputRoot, stagingOutput, readyGeneration, generationRenamed = false, pointerRenamed = false;
  try {
    assertNoSymlinkPath(workspace, requested.legacyRoot, { allowMissing: false }); lock = acquireProjectLockImmediate(requested.legacyRoot ?? ROOT, { ownerId: `book-build-${process.pid}` });
    project = resolveBookProject(requested.legacyRoot, { workspaceRoot: workspace }); if (pinnedProjectCanonicalHash(project) !== pinnedProjectCanonicalHash(requested)) throw new Error("Caller Book Project snapshot is stale; rediscover it and start a fresh build."); hooks.afterRediscovery?.({ project }); assertCurrentProjectIdentity(project);
    { let ancestor = physicalOutputRoot; while (!existsSync(ancestor)) ancestor = dirname(ancestor); ensurePhysicalDirectory(pinPhysicalDirectory(ancestor).path, physicalOutputRoot); }
    stagingGeneration = resolve(physicalOutputRoot, ".staging", `${project.id}-${token}`); stagingBuild = resolve(stagingGeneration, "build"); stagingOutputRoot = resolve(stagingGeneration, "output-root"); stagingOutput = resolve(stagingOutputRoot, project.id); ensurePhysicalDirectory(physicalOutputRoot, resolve(stagingBuild, "diagrams")); ensurePhysicalDirectory(physicalOutputRoot, stagingOutput);
    const combinedFile = resolve(stagingBuild, "combined.md"), assembled = assembleBook(project, { diagramsDirectory: resolve(stagingBuild, "diagrams") }); writeFileSync(combinedFile, assembled.markdown);
    const shared = [combinedFile, "--from=markdown+yaml_metadata_block", "--standalone", "--toc", `--resource-path=${[stagingBuild, project.root, ROOT].join(delimiter)}`];
    for (const profile of outputDispatch(project)) {
      const output = projectOutputPath(project, stagingOutputRoot, profile.format);
      if (profile.format === "html") run("pandoc", [...shared, "--to=html5", "--embed-resources", `--css=${resolve(ROOT, "publishing", "styles.css")}`, "--output", output]);
      else if (profile.format === "epub") run("pandoc", [...shared, "--to=epub3", `--css=${resolve(ROOT, "publishing", "epub.css")}`, "--output", output]);
      else throw new Error(`Book Project ${project.id} declares PDF output ${profile.path}, but no generic PDF renderer capability is configured.`);
    }
    hooks.afterRender?.({ project, buildDirectory: stagingBuild, outputDirectory: stagingOutput }); assertCurrentProjectIdentity(project); const outputs = verifyOutputs(project, { outputRoot: stagingOutputRoot });
    const stagingRecord = treeRecord(stagingGeneration); syncGenerationTree(stagingGeneration, hooks); assertTree(stagingRecord); readyGeneration = resolve(physicalOutputRoot, ".generations", project.id, token); ensurePhysicalDirectory(physicalOutputRoot, dirname(readyGeneration)); hooks.beforeGenerationReady?.({ project, generation: readyGeneration, staging: stagingGeneration }); assertTree(stagingRecord); if (existsSync(readyGeneration)) throw new Error("Generic build generation destination already exists."); hooks.beforeGenerationRename?.({ project, generation: readyGeneration, staging: stagingGeneration }); assertTree(stagingRecord); if (existsSync(readyGeneration)) throw new Error("Generic build generation destination changed before rename."); const stagingParent = dirname(stagingGeneration), generationParent = dirname(readyGeneration); renameSync(stagingGeneration, readyGeneration); generationRenamed = true; if (existsSync(stagingGeneration)) throw new Error("Generic build staging remained after generation rename."); assertTree(stagingRecord, readyGeneration); syncPath(stagingParent, "staging-parent", hooks); syncPath(generationParent, "generation-parent", hooks); hooks.afterGenerationReady?.({ project, generation: readyGeneration });
    buildDirectory = resolve(readyGeneration, "build"); outputDirectory = resolve(readyGeneration, "output-root", project.id); const currentDirectory = resolve(physicalOutputRoot, ".current"), current = resolve(currentDirectory, `${project.id}.json`); ensurePhysicalDirectory(physicalOutputRoot, currentDirectory); assertNoSymlinkPath(physicalOutputRoot, current); const pointerParent = pinPhysicalEntry(currentDirectory, "directory"), priorPointer = existsSync(current) ? pinPhysicalEntry(current, "file") : null;
    const temporary = `${current}.${token}.tmp`, pointerBytes = Buffer.from(`${JSON.stringify({ schemaVersion: 1, projectId: project.id, generation: token })}\n`), pointerFd = openSync(temporary, "wx", 0o600); hooks.durability?.("before-fsync-pointer-file", temporary); try { writeFileSync(pointerFd, pointerBytes); fsyncSync(pointerFd); } finally { closeSync(pointerFd); } hooks.durability?.("after-fsync-pointer-file", temporary); const temporaryIdentity = pinPhysicalEntry(temporary, "file"); if (!readFileSync(temporary).equals(pointerBytes)) throw new Error("Generic build pointer temporary bytes changed before atomic switch."); hooks.beforeGenerationSwitch?.({ project, generation: readyGeneration, pointer: current }); assertPinnedEntry(pointerParent, "directory"); assertPinnedEntry(temporaryIdentity, "file"); if (priorPointer) assertPinnedEntry(priorPointer, "file"); else if (existsSync(current)) throw new Error("Generic build generation pointer changed before atomic switch."); renameSync(temporary, current); pointerRenamed = true; syncPath(currentDirectory, "pointer-parent", hooks); hooks.afterPointerRename?.({ project, generation: readyGeneration, pointer: current }); const currentIdentity = pinPhysicalEntry(current, "file"); if (currentIdentity.dev !== temporaryIdentity.dev || currentIdentity.ino !== temporaryIdentity.ino || !readFileSync(current).equals(pointerBytes)) throw new Error("Generic build generation pointer was replaced during atomic switch."); hooks.afterGenerationSwitch?.({ project, generation: readyGeneration, pointer: current }); retainGenerations(physicalOutputRoot, generationParent, current, project.id, hooks);
    return { project, buildDirectory, outputDirectory, combinedFile: resolve(buildDirectory, "combined.md"), diagramCount: assembled.diagramCount, generation: token, generationPointer: current, outputs: outputs.map((item) => ({ ...item, file: resolve(outputDirectory, relative(stagingOutput, item.file)) })) };
  } catch (error) {
    if (stagingGeneration) rmSync(stagingGeneration, { recursive: true, force: true }); if (readyGeneration && generationRenamed && !pointerRenamed) rmSync(readyGeneration, { recursive: true, force: true });
    throw error;
  } finally { lock?.release(); workspaceLock.release(); }
}
if (import.meta.url === new URL(process.argv[1], "file:").href) {
  const project = resolveBookProject(process.argv[2]);
  if (project.outputProfiles.some((profile) => profile.format === "pdf")) { const result = await buildRelease(project); console.log(`✓ HTML, PDF, and EPUB candidate ${result.candidate.candidateHash}`); }
  else { const result = buildProject(project); console.log(`✓ ${result.project.chapters.length} chapters and ${result.project.parts.length} parts discovered for ${result.project.id}.`); for (const output of result.outputs) console.log(`✓ ${basename(output.file)} verified (${output.size} bytes)`); }
}
