import { resolve } from "node:path";
import { ROOT } from "../lib.mjs";

export const RESEARCH_SCHEMA_VERSION = 1;
export const RESEARCH_GENERATOR_VERSION = "1";
export const RESEARCH_ROOT = resolve(ROOT, "research", "topics");
export const RESEARCH_MANIFEST = "research.yaml";
export const RESEARCH_OUTPUT = "outputs/research-brief.md";
export const RESEARCH_STATE = ".rtb-publishing/research-state.json";
export const RESEARCH_MARKER = "<!-- Generated by RTB Publishing Research. Source: research.yaml. -->";
export const RESEARCH_SCHEMA_DIRECTORY = resolve(ROOT, "schemas", "research");

export const RECORD_DIRECTORIES = Object.freeze({
  source: "sources",
  evidence: "evidence",
  claim: "claims"
});
